title: Lydia Li # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>UX Design</b> & <b>Engineering</b> background
  <br>
  Previously @<a href="https://www.microsoft.com/en-ca">Microsoft</a>, <a href="https://www.nvidia.com/en-us/">Nvidia</a>, <a href="https://www.ford.ca/">Ford</a>
  <br>
  <b>Master of Information</b> @<a href="https://ischool.utoronto.ca/current-students/programs-courses/programs-of-study/master-of-information/user-experience-design-uxd/">UofT</a>
  <br><br>
  <a href="/pdf/Youjing_Li_Data_Resum.pdf">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/lydialiuw/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.instagram.com/lazi.li/">View My Visual Blog</a>

  
theme: jekyll-theme-minimal	
google_analytics: UA-155132691-1 # your Google Analytics tracking ID here
