title: Lydia Li # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I am a business-savvy engineer and designer. 
  <br><br>
  Fascinated by the intersection between design and technology, I specialize in applications that are powered by data and AI. Through human-centered design and product thinking, I love engaging in purpose-driven work that produces practical results and business values.
  <br><br>
  <a href="https://www.linkedin.com/in/lydialiuw/">View My LinkedIn Profile</a> 
  
